# Generated by Django 3.2.5 on 2021-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=50)),
                ('team2', models.CharField(max_length=50)),
                ('odds1', models.DecimalField(decimal_places=2, max_digits=5)),
                ('odds2', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
